# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WYyvkyJ7WjwEMjrO76aocKBTdAL-P6R

# Proyek Akhir Klasifikasi Gambar
**Nama:** Awanda Rosi Firdaus
**Email:** awrosifi17@gmail.com

Dataset: CIFAR-10
"""

!pip install tensorflowjs scikit-learn matplotlib

import os
import zipfile
import shutil
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
import tensorflowjs as tfjs

print(f"TensorFlow Version: {tf.__version__}")

# 1. Load Dataset CIFAR-10
# CIFAR-10 memenuhi syarat wajib: > 1000 gambar, 10 kelas.
(x_train_full, y_train_full), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalize pixel values (0-1)
x_train_full = x_train_full.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

y_train_full = y_train_full.squeeze()
y_test = y_test.squeeze()

# 2. Splitting Data (Train, Validation, Test)
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full, y_train_full, test_size=0.2, stratify=y_train_full, random_state=42
)

print(f"Train images: {x_train.shape[0]}")
print(f"Validation images: {x_val.shape[0]}")
print(f"Test images: {x_test.shape[0]}")

# 3. Arsitektur Model Sequential dengan Conv2D & MaxPooling2D
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 3)),

    # Block 1
    tf.keras.layers.Conv2D(32, (3,3), padding='same', activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(32, (3,3), padding='same', activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Dropout(0.25),

    # Block 2
    tf.keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Dropout(0.35),

    # Block 3
    tf.keras.layers.Conv2D(128, (3,3), padding='same', activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(128, (3,3), padding='same', activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(pool_size=(2,2)),
    tf.keras.layers.Dropout(0.45),

    # Dense Layers (Classification Head)
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# 4. Setup Callbacks (Early Stopping & Reduce LR)
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=3,
        verbose=1
    )
]

# 5. Data Augmentation (Membantu meningkatkan akurasi menghindari overfitting)
datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
)
datagen.fit(x_train)

# 6. Proses Training
history = model.fit(
    datagen.flow(x_train, y_train, batch_size=64),
    validation_data=(x_val, y_val),
    epochs=50,
    callbacks=callbacks
)

# 7. Evaluasi pada Test Set (Syarat: > 85%)
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\nTest Accuracy: {test_acc*100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

# 8. Membuat Plot Akurasi dan Loss (Syarat Wajib)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['accuracy'], label='Train Accuracy')
axes[0].plot(history.history['val_accuracy'], label='Validation Accuracy')
axes[0].set_title('Model Accuracy')
axes[0].set_ylabel('Accuracy')
axes[0].set_xlabel('Epoch')
axes[0].legend(loc='lower right')
axes[0].grid(True)

axes[1].plot(history.history['loss'], label='Train Loss')
axes[1].plot(history.history['val_loss'], label='Validation Loss')
axes[1].set_title('Model Loss')
axes[1].set_ylabel('Loss')
axes[1].set_xlabel('Epoch')
axes[1].legend(loc='upper right')
axes[1].grid(True)

plt.show()

# 9. Menyimpan Model ke Format SavedModel, TFLite, dan TFJS (Syarat Wajib)

# Buat direktori jika belum ada
os.makedirs('saved_model', exist_ok=True)
os.makedirs('tflite', exist_ok=True)
os.makedirs('tfjs_model', exist_ok=True)

# A. Export as SavedModel
print("Exporting SavedModel...")
model.export('saved_model')

# B. Export as TF-Lite
print("Exporting TFLite...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('tflite/model.tflite', 'wb') as f:
    f.write(tflite_model)

# Buat label.txt untuk TFLite
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
with open('tflite/label.txt', 'w') as f:
    f.write('\n'.join(class_names))

# C. Export as TFJS
print("Exporting TFJS...")
tfjs.converters.save_keras_model(model, 'tfjs_model')

print("\nSemua model berhasil di-export!")

# 10. Persiapan Akhir Submission (MOHON DIBACA)
print("✅ Proses training dan export model SELESAI!")
print("\n⚠️ LAKUKAN LANGKAH INI SECARA MANUAL AGAR TIDAK DITOLAK REVIEWER:")
print("1. Di pojok kiri atas Colab, klik menu 'File' -> 'Download' -> 'Download .ipynb'.")
print("2. Di menu yang sama, klik 'File' -> 'Download' -> 'Download .py'.")
print("3. Buka ikon Folder di panel kiri Colab. Anda akan melihat folder 'saved_model', 'tfjs_model', dan 'tflite'.")
print("   Untuk men-download folder tersebut, zip masing-masing folder dengan run cell tambahan di bawah jika perlu, atau download isinya satu-satu.")
print("4. Download juga file 'requirements.txt'.")
print("5. Di komputer Anda, jadikan SEMUA file (.ipynb, .py, requirements.txt, beserta KETIGA folder model) ke dalam satu folder.")
print("6. Klik kanan folder tersebut -> Compress to ZIP, dan kirim file ZIP buatan Anda sendiri tersebut ke Dicoding.")

# Buat requirements.txt (Syarat Wajib)
reqs = """tensorflow\n"
"tensorflowjs\n"
"matplotlib\n"
"scikit-learn\n"""
with open("requirements.txt", "w") as f:
    f.write(reqs)

# Bantuan auto-zip HANYA UNTUK FOLDER MODEL agar mudah didownload dari Colab:
import shutil
shutil.make_archive('saved_model', 'zip', 'saved_model')
shutil.make_archive('tfjs_model', 'zip', 'tfjs_model')
shutil.make_archive('tflite', 'zip', 'tflite')
print("\n(Tiga folder model telah dizip untuk mempermudah proses download Anda dari panel kiri Colab)")